---
- hosts: "all"
  become: true
  roles:
    - prometheus
    - node_exporter
    - elasticsearch
    - kibana  
    - certs
    - fluentbit

  tasks:
  - name: "Firewall ports enable"
    ansible.builtin.firewalld:
     port: "{{ item }}/tcp"
     permanent: true
     state: enabled
    loop:
    - 9200
    - 5601
    - 9090
    become: true

  - name: "Reload firewalld to apply changes"
    ansible.builtin.command: firewall-cmd --reload
    become: true

  - name: "Restart EFK stack"
    ansible.builtin.systemd:
     name: "{{ item }}"
     state: restarted
     enabled: true
    loop:
    - elasticsearch
    - kibana
    - fluentbit
    become: true

