---
- hosts: "all"
  become: true
  roles:
    - elasticsearch
    - kibana
    - logstash  
    - certs

  tasks:
  - name: "Firewall ports enable"
    ansible.builtin.firewalld:
     port: "{{ item }}/tcp"
     permanent: true
     state: enabled
    loop:
    - 9200
    - 5601
    become: true

  - name: "Reload firewalld to apply changes"
    ansible.builtin.command: firewall-cmd --reload
    become: true

  - name: "Restart ElK stack"
    ansible.builtin.systemd:
     name: "{{ item }}"
     state: restarted
     enabled: true
    loop:
    - elasticsearch
    - kibana
    - logstash
    become: true

