- name: Copy Prometheus configuration
      template:
        src: prometheus.yml.j2
        dest: "{{ prometheus_config_file }}"
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
        mode: '0644'
      notify: Restart Prometheus
