- name: Create Prometheus user
      user:
        name: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
        createhome: no
        shell: /sbin/nologin
- name: Create required directories
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
        mode: '0755'
      loop:
        - "{{ prometheus_dir }}"
        - "{{ prometheus_data_dir }}"

    - name: Download and extract Prometheus
      get_url:
        url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
        dest: "/tmp/prometheus.tar.gz"

    - name: Extract Prometheus binaries
      unarchive:
        src: "/tmp/prometheus.tar.gz"
        dest: "/tmp"
        remote_src: yes

    - name: Move binaries to /usr/local/bin
      copy:
        src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
        dest: "{{ prometheus_bin_dir }}/{{ item }}"
        mode: '0755'
        remote_src: yes
      loop:
        - prometheus
        - promtool
