prometheus_version: "2.45.0"
    prometheus_user: "prometheus"
    prometheus_group: "prometheus"
    prometheus_dir: "/etc/prometheus"
    prometheus_data_dir: "/var/lib/prometheus"
    prometheus_bin_dir: "/usr/local/bin"
    prometheus_config_file: "{{ prometheus_dir }}/prometheus.yml"
    prometheus_web_listen_address: "0.0.0.0:9090"
